---
- name: Converge
  hosts: all

  tasks:
    - name: Ensure sudo is installed.
      ansible.builtin.dnf:
        name: sudo
        state: present

    - name: Ensure EPEL repo is enabled.
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: "Include palekiwi.neovim_ansible"
      ansible.builtin.include_role:
        name: "palekiwi.neovim_ansible"

    - name: Cat contents of config-packer.lua
      ansible.builtin.command:
        cmd: "cat ~/.config/nvim/lua/config-packer.lua"
      changed_when: false
      register: configpacker

    - name: Cat contents of config-packer.lua
      ansible.builtin.debug:
        var: configpacker.stdout_lines

    - name: Cat contents of init.lua
      ansible.builtin.command:
        cmd: "cat ~/.config/nvim/init.lua"
      changed_when: false
      register: init

    - name: Cat contents of init.lua
      ansible.builtin.debug:
        var: init.stdout_lines
