---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    #image: quay.io/rockylinux/rockylinux:9
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
